---
sidebar: sidebar 
permalink: trident-install/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. 
---
= Implementar el operador de Trident con Helm (modo sin conexiĂ³n)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desplegar el operador Trident e instalar Trident con Helm. Este proceso se aplica a instalaciones en las que las imĂ¡genes de contenedor requeridas por Trident se almacenan en un registro privado. Si no dispone de un registro de imĂ¡genes privado, utilice el link:kubernetes-deploy-helm.html["proceso de implementaciĂ³n estĂ¡ndar"].



== InformaciĂ³n crĂ­tica sobre Trident 24,10

*Debe leer la siguiente informaciĂ³n crĂ­tica sobre Trident.*

.<strong>InformaciĂ³n crĂ­tica sobre Trident </strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1,32 ahora es compatible con Trident. Actualizar Trident antes de actualizar Kubernetes.
* Trident aplica estrictamente el uso de la configuraciĂ³n de mĂºltiples rutas en entornos SAN, con un valor recomendado de `find_multipaths: no` en archivo multipath.conf.
+
El uso de una configuraciĂ³n que no sea multivĂ­a o el uso `find_multipaths: yes` o `find_multipaths: smart` un valor en el archivo multipath.conf provocarĂ¡ errores de montaje. Trident ha recomendado el uso de `find_multipaths: no` desde la versiĂ³n 21,07.



=====
====


== Despliegue el operador Trident e instale Trident usando Helm

Con Trident link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Carta del timĂ³n"^]puede desplegar el operador Trident e instalar Trident en un solo paso.

Revisa link:../trident-install/kubernetes-deploy.html["descripciĂ³n general de la instalaciĂ³n"] para asegurarte de que cumpliste los requisitos previos de instalaciĂ³n y seleccionaste la opciĂ³n de instalaciĂ³n correcta para tu entorno.

.Antes de empezar
AdemĂ¡s de link:../trident-install/kubernetes-deploy.html#before-you-deploy["requisitos previos a la implementaciĂ³n"] tĂº necesitas link:https://v3.helm.sh/["VersiĂ³n timĂ³n 3"^].


IMPORTANT: Al instalar Trident en un repositorio privado, si estĂ¡ utilizando el `imageRegistry` conmutador para especificar la ubicaciĂ³n del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio.

.Pasos
. AĂ±ada el repositorio Helm de Trident:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Utilice `helm install` y especifique un nombre para el despliegue y la ubicaciĂ³n del registro de imĂ¡genes. link:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["ImĂ¡genes Trident y CSI"]Puede estar ubicado en un registro o registros diferentes, pero todas las imĂ¡genes CSI deben estar ubicadas en el mismo registro. En los ejemplos, `100.2410.0` es la versiĂ³n de Trident que estĂ¡ instalando.
+
[role="tabbed-block"]
====
.ImĂ¡genes en un registro
--
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2410.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.ImĂ¡genes en diferentes registros
--
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2410.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:24.10.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:24.10 --set tridentImage=<your-registry>/trident:24.10.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Si ya creĂ³ un espacio de nombres para Trident, `--create-namespace` el parĂ¡metro no crearĂ¡ un espacio de nombres adicional.



Puede utilizar `helm list` para revisar detalles de instalaciĂ³n como nombre, espacio de nombres, grĂ¡fico, estado, versiĂ³n de la aplicaciĂ³n, y nĂºmero de revisiĂ³n.



== Pasar los datos de configuraciĂ³n durante la instalaciĂ³n

Existen dos formas de pasar los datos de configuraciĂ³n durante la instalaciĂ³n:

[cols="2"]
|===
| OpciĂ³n | DescripciĂ³n 


| `--values` (o `-f`)  a| 
Especifique un archivo YAML con anulaciones. Esto se puede especificar varias veces y el archivo de la derecha tendrĂ¡ prioridad.



| `--set`  a| 
Especifique anulaciones en la lĂ­nea de comandos.

|===
Por ejemplo, para cambiar el valor predeterminado de `debug`, ejecute el siguiente comando donde `100.2410.0` es la versiĂ³n de Trident que estĂ¡ instalando:

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2410.0  --create-namespace --namespace trident --set tridentDebug=true
----
Para agregar el valor nodePrep, ejecute el siguiente comando:

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2406.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== Opciones de configuraciĂ³n

Esta tabla y el `values.yaml` archivo, que forma parte del diagrama Helm, proporcionan la lista de claves y sus valores predeterminados.


WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplĂ­e la afinidad predeterminada.

[cols="3"]
|===
| OpciĂ³n | DescripciĂ³n | Predeterminado 


| `nodeSelector` | Etiquetas de nodo para la asignaciĂ³n de pod |  


| `podAnnotations` | Anotaciones del pod |  


| `deploymentAnnotations` | Anotaciones de despliegue |  


| `tolerations` | Toleraciones para la asignaciĂ³n de POD |  


| `affinity` | Afinidad para la asignaciĂ³n de pod  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: No elimine la afinidad predeterminada del archivo values.yaml. Cuando desee proporcionar una afinidad personalizada, amplĂ­e la afinidad predeterminada.



| `tridentControllerPluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s informaciĂ³n. |  


| `tridentControllerPluginTolerations` | Anula la toleraciĂ³n de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s informaciĂ³n. |  


| `tridentNodePluginNodeSelector` | Selectores de nodos adicionales para POD. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s informaciĂ³n. |  


| `tridentNodePluginTolerations` | Anula la toleraciĂ³n de Kubernetes en pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["DescripciĂ³n de los pods de la controladora y los pods de nodo"] para obtener mĂ¡s informaciĂ³n. |  


| `imageRegistry` | Identifica el registro de `trident-operator` , `trident` y otras imĂ¡genes. DĂ©jelo vacĂ­o para aceptar el valor predeterminado. IMPORTANTE: Al instalar Trident en un repositorio privado, si estĂ¡ utilizando el `imageRegistry` conmutador para especificar la ubicaciĂ³n del repositorio, no lo utilice `/netapp/` en la ruta de acceso del repositorio. | "" 


| `imagePullPolicy` | Establece la polĂ­tica de extracciĂ³n de imĂ¡genes para la `trident-operator`. | `IfNotPresent` 


| `imagePullSecrets` | Define los secretos de extracciĂ³n de imĂ¡genes para `trident-operator` , `trident` y otras imĂ¡genes. |  


| `kubeletDir` | Permite anular la ubicaciĂ³n del host del estado interno de kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite definir el nivel de log del operador Trident en: `trace`, , , , `debug`, , `info` `warn` `error` O `fatal`. | `"info"` 


| `operatorDebug` | Permite configurar en debug el nivel de registro del operador Trident. | `true` 


| `operatorImage` | Permite la sustituciĂ³n completa de la imagen para `trident-operator`. | "" 


| `operatorImageTag` | Permite sobrescribir la etiqueta de la `trident-operator` imagen. | "" 


| `tridentIPv6` | Permite permitir que Trident funcione en clĂºsteres de IPv6. | `false` 


| `tridentK8sTimeout` | Anula el tiempo de espera predeterminado de 30 segundos para la mayorĂ­a de las operaciones de la API de Kubernetes (si no es cero, en segundos). | `0` 


| `tridentHttpRequestTimeout` | Sustituye el timeout por defecto de 90 segundos para las solicitudes HTTP, `0s` siendo una duraciĂ³n infinita para el timeout. No se permiten valores negativos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite deshabilitar la generaciĂ³n de informes periĂ³dicos de AutoSupport de Trident. | `false` 


| `tridentAutosupportImageTag` | Permite sobrescribir la etiqueta de la imagen para el contenedor Trident AutoSupport. | `<version>` 


| `tridentAutosupportProxy` | Permite al contenedor Trident AutoSupport llamar a casa a travĂ©s de un proxy HTTP. | "" 


| `tridentLogFormat` | Define el formato de registro de Trident (`text`o `json`). | `"text"` 


| `tridentDisableAuditLog` | Deshabilita el registrador de auditorĂ­as de Trident. | `true` 


| `tridentLogLevel` | Permite definir el nivel de log de Trident en: `trace`, , , , , `debug`, `info` `warn` `error` O `fatal`. | `"info"` 


| `tridentDebug` | Permite establecer el nivel de registro de Trident en `debug`. | `false` 


| `tridentLogWorkflows` | Permite habilitar flujos de trabajo de Trident especĂ­ficos para el registro de seguimiento o la supresiĂ³n de registros. | "" 


| `tridentLogLayers` | Permite activar capas de Trident especĂ­ficas para el registro de rastreo o la supresiĂ³n de registros. | "" 


| `tridentImage` | Permite la sustituciĂ³n completa de la imagen para Trident. | "" 


| `tridentImageTag` | Permite sobrescribir la etiqueta de la imagen para Trident. | "" 


| `tridentProbePort` | Permite sobrescribir el puerto predeterminado utilizado para las sondas de vida/preparaciĂ³n de Kubernetes. | "" 


| `windows` | Permite instalar Trident en el nodo de trabajo de Windows. | `false` 


| `enableForceDetach` | Permite habilitar la funciĂ³n Forzar separaciĂ³n. | `false` 


| `excludePodSecurityPolicy` | Excluye la polĂ­tica de seguridad del pod del operador de la creaciĂ³n. | `false` 


| `nodePrep` | Permite a Trident preparar los nodos del clĂºster de Kubernetes para gestionar volĂºmenes mediante el protocolo de almacenamiento de datos especificado. *Actualmente, `iscsi` es el Ăºnico valor soportado.* |  
|===